name: Build & Publish

env:
  BUILD_TYPE: Release

# Default: minimal; einzelne Jobs erweitern das selbst
permissions: {}

on:
  push:
    paths-ignore:
      - "docfx/**"
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      gitversion_semver: ${{ steps.gitversion.outputs.semVer }}
      gitversion_fullsemver: ${{ steps.gitversion.outputs.fullSemVer }}
      gitversion_assemblysemver: ${{ steps.gitversion.outputs.assemblySemVer }}
      gitversion_informationalversion: ${{ steps.gitversion.outputs.informationalVersion }}
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: 6.0.x

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1
        with:
          useConfigFile: true

  build_windows:
    needs: setup
    runs-on: windows-latest
    steps:
      - name: Prepare env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "SEMVER=${{ needs.setup.outputs.gitversion_semver }}" >> $GITHUB_ENV

      - name: Visual Studio environment
        shell: cmd
        run: |
          :: See https://github.com/microsoft/vswhere/wiki/Find-VC
          for /f "usebackq delims=*" %%i in (`vswhere -latest -property installationPath`) do (
            call "%%i"\Common7\Tools\vsdevcmd.bat -arch=x64 -host_arch=x64
          )
          :: kein globales Dumpen aller ENV-Variablen

      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ..
          cmake --build . --config ${{ env.BUILD_TYPE }} -- /m:16

      - name: Clean build directory
        run: |
          mkdir -p build/addons/counterstrikesharp/bin/win64
          mv build/${{ env.BUILD_TYPE }}/*.dll build/addons/counterstrikesharp/bin/win64
          mkdir build/output/
          mv build/addons build/output

      - uses: actions/upload-artifact@v4
        with:
          name: counterstrikesharp-windows-${{ needs.setup.outputs.gitversion_semver }}
          path: build/output/

  build_linux:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
    steps:
      - name: Prepare env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "SEMVER=${{ needs.setup.outputs.gitversion_semver }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ..
          cmake --build . --config ${{ env.BUILD_TYPE }} -- -j16

      - name: Clean build directory
        run: |
          mkdir build/output/
          mv build/addons build/output

      - uses: actions/upload-artifact@v4
        with:
          name: counterstrikesharp-linux-${{ needs.setup.outputs.gitversion_semver }}
          path: build/output/

  build_managed:
    needs: setup
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Prepare env
        shell: bash
        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Setup .NET SDK 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore managed/CounterStrikeSharp.sln

      - name: Run tests
        run: dotnet test --logger trx --results-directory "TestResults-${{ needs.setup.outputs.gitversion_semver }}" managed/CounterStrikeSharp.API.Tests/CounterStrikeSharp.API.Tests.csproj

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ needs.setup.outputs.gitversion_semver }}
          path: TestResults-${{ needs.setup.outputs.gitversion_semver }}
        if: ${{ always() }}

      - name: Publish artifacts (managed)
        run: |
          dotnet publish -c Release \
            /p:Version=${{ needs.setup.outputs.gitversion_semver }} \
            /p:AssemblyVersion=${{ needs.setup.outputs.gitversion_assemblySemver }} \
            /p:InformationalVersion=${{ needs.setup.outputs.gitversion_informationalversion }} \
            managed/CounterStrikeSharp.API
          
          # Pack mit eigener PackageId für GitHub Packages (keine csproj-Änderung nötig)
          dotnet pack -c Release \
            /p:PackageId=BlueRoyal.CounterStrikeSharp.API \
            /p:Version=${{ needs.setup.outputs.gitversion_semver }} \
            /p:AssemblyVersion=${{ needs.setup.outputs.gitversion_assemblySemver }} \
            /p:InformationalVersion=${{ needs.setup.outputs.gitversion_informationalversion }} \
            managed/CounterStrikeSharp.API

      - uses: actions/upload-artifact@v4
        with:
          name: counterstrikesharp-api-${{ needs.setup.outputs.gitversion_semver }}
          path: managed/CounterStrikeSharp.API/bin/Release

  publish:
    # Release & GitHub Packages nur auf Tags in DEINEM Fork
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.repository == 'BlueRoyal/CounterStrikeSharp' }}
    permissions:
      contents: write
      packages: write   # wichtig für GitHub Packages Push
    needs: ["setup", "build_linux", "build_windows", "build_managed"]
    runs-on: ubuntu-latest
    steps:
      - name: Prepare env
        shell: bash
        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: counterstrikesharp-windows-${{ needs.setup.outputs.gitversion_semver }}
          path: build/windows

      - uses: actions/download-artifact@v4
        with:
          name: counterstrikesharp-linux-${{ needs.setup.outputs.gitversion_semver }}
          path: build/linux

      - uses: actions/download-artifact@v4
        with:
          name: counterstrikesharp-api-${{ needs.setup.outputs.gitversion_semver }}
          path: build/api

      - name: Add API to Artifacts
        run: |
          mkdir -p build/linux/addons/counterstrikesharp/api
          mkdir -p build/windows/addons/counterstrikesharp/api
          cp -r build/api/net8.0/publish/* build/linux/addons/counterstrikesharp/api
          cp -r build/api/net8.0/publish/* build/windows/addons/counterstrikesharp/api

      - name: Zip Builds
        run: |
          (cd build/linux && zip -qq -r ../../counterstrikesharp-linux-${{ needs.setup.outputs.gitversion_semver }}.zip *)
          (cd build/windows && zip -qq -r ../../counterstrikesharp-windows-${{ needs.setup.outputs.gitversion_semver }}.zip *)

      - name: Add dotnet runtime
        run: |
          mkdir -p build/linux/addons/counterstrikesharp/dotnet
          curl -s -L https://download.visualstudio.microsoft.com/download/pr/c1371dc2-eed2-47be-9af3-ae060dbe3c7d/bd509e0a87629764ed47608466d183e6/aspnetcore-runtime-8.0.3-linux-x64.tar.gz \
          | tar xvz -C build/linux/addons/counterstrikesharp/dotnet

          mkdir -p build/windows/addons/counterstrikesharp/dotnet
          curl -s -L https://download.visualstudio.microsoft.com/download/pr/086d1dd6-57a5-437a-a1ef-549cf702fb48/dd4a8fe6c53a1016a414d6f2925c1323/aspnetcore-runtime-8.0.3-win-x64.zip -o dotnet.zip
          unzip -qq dotnet.zip -d build/windows/addons/counterstrikesharp/dotnet

      - name: Zip Builds (with runtime)
        run: |
          (cd build/linux && zip -qq -r ../../counterstrikesharp-with-runtime-linux-${{ needs.setup.outputs.gitversion_semver }}.zip *)
          (cd build/windows && zip -qq -r ../../counterstrikesharp-with-runtime-windows-${{ needs.setup.outputs.gitversion_semver }}.zip *)
      
      # Changelog generieren -> Datei, nicht als riesiger Input-String
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --current -s footer

      - name: Write changelog to file
        run: |
          printf "%s" "${{ steps.git-cliff.outputs.content }}" > CHANGELOG.md

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          body_path: CHANGELOG.md
          files: |
            counterstrikesharp-windows-${{ needs.setup.outputs.gitversion_semver }}.zip
            counterstrikesharp-with-runtime-windows-${{ needs.setup.outputs.gitversion_semver }}.zip
            counterstrikesharp-linux-${{ needs.setup.outputs.gitversion_semver }}.zip
            counterstrikesharp-with-runtime-linux-${{ needs.setup.outputs.gitversion_semver }}.zip

      # ----- GitHub Packages (NuGet) Push -----
      - name: Add GitHub Packages source
        run: |
          dotnet nuget remove source github || true
          dotnet nuget add source "https://nuget.pkg.github.com/BlueRoyal/index.json" \
            --name "github" \
            --username BlueRoyal \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text

      - name: Push to GitHub Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Anzeige, wo die nupkg liegt
          find . -name "BlueRoyal.CounterStrikeSharp.API*.nupkg" -print
          dotnet nuget push **/BlueRoyal.CounterStrikeSharp.API*.nupkg \
            --source "github" \
            --skip-duplicate

      - name: Send Notification to Discord
        if: ${{ env.DISCORD_WEBHOOK != '' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            A new release of CS# has been tagged [v${{ needs.setup.outputs.gitversion_semver }}](${{ steps.release.outputs.url }})

            ${{ steps.git-cliff.outputs.content }}

            Please refer to [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
